<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" Sdk="Microsoft.NET.Sdk">
  <Target Name="Default"></Target>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>PowerServeClient</AssemblyName>
    <Authors>Justin Grote</Authors>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <PropertyGroup Label="AOT">
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Speed</OptimizationPreference>
    <IlcGenerateMstatFile>true</IlcGenerateMstatFile>
    <IlcGenerateDgmlFile>true</IlcGenerateDgmlFile>
    <StackTraceSupport>false</StackTraceSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <Compile Include="../Shared/StreamString.cs" />
  </ItemGroup>

  <Target Name="CopyToBuildFolder" AfterTargets="Publish">
    <Copy SourceFiles="$(OutputPath)\native\PowerServeClient.exe" DestinationFolder="../../Build" />
  </Target>
</Project>