<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" Sdk="Microsoft.NET.Sdk">
  <Target Name="Default"></Target>
  <PropertyGroup>
    <AssemblyName>PowerServe</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.Commands.Utility" />
    <PackageReference Include="System.Management.Automation" PrivateAssets="all" />
    <Compile Include="../Shared/StreamString.cs" />
  </ItemGroup>

  <Target Name="CopyToBuildFolder" AfterTargets="Publish">
    <Copy SourceFiles="$(OutDir)\PowerServe.dll" DestinationFolder="../../Build" />
  </Target>
</Project>